chemblog/urls.py
from django.urls import path
from . import views

app_name = 'chemblog'

urlpatterns = [
    path('', views.index, name='index'),
    path('post/<int:post_id>/', views.post_detail, name='post_detail'),
    path('post/create/', views.post_create, name='post_create'),
    path('post/modify/<int:post_id>', views.post_modify, name='post_modify'),
    path('post/delete/<int:post_id>', views.post_delete, name='post_delete'),
    path('post/vote/<int:post_id>', views.post_vote, name='post_vote'),
    path('comment/vote/<int:comment_id>', views.comment_vote, name='comment_vote'),
    path('comment/delete<int:comment_id>', views.comment_delete, name='comment_delete'),
]

common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from django.utils import timezone


class DynamicContextLoginView(auth_views.LoginView):
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['time'] = timezone.now()
        return context


app_name = 'common'

urlpatterns = [
    path('naverlogin_reprompt', views.naverlogin_reprompt, name='naverlogin_reprompt'),
    path('signup_naver/<str:access_token>/', views.signup_naver, name='signup_naver'),
    path('naverlogin/', views.naverlogin, name='naverlogin'),
    path('navercallback/', views.navercallback, name='navercallback'),
    path('user_profile/', views.user_profile, name='user_profile'),
    path('signup_kakao/<str:access_token>/', views.signup_kakao, name='signup_kakao'),
    path('login/', DynamicContextLoginView.as_view(template_name='common/login.html'), name='login'),
    path('kakaologin/', views.kakaologin, name='kakaologin'),
    path('kakaocallback/', views.kakaocallback, name='kakaocallback'),
    path('logout/', auth_views.LogoutView.as_view(template_name='chemblog/index.html'), name='logout'),
    path('signup/', views.signup, name='signup'),
    path('password_reset/', auth_views.PasswordResetView.as_view(
        email_template_name='common/password_reset_email.html', success_url='done'
    ),
         name='password_reset'
         ),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password_reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        success_url='http://localhost:8000/common/password_reset_complete/'
    ),
         name='password_reset_confirm'),
    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('chemblog/', include('chemblog.urls')),
    path('common/', include('common.urls')),
    path('socialaccounts/', include('allauth.urls')),
]

handler404 = 'common.views.page_not_found'
handler500 = 'common.views.server_error'

chemblog/models.py
from django.db import models
from django.contrib.auth.models import User


class Post(models.Model):
    subject = models.CharField(max_length=200)
    content = models.TextField()
    pub_date = models.DateTimeField()
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_post')
    modify_date = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(User, related_name='voter_post')
    hits = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.subject


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    comment = models.TextField()
    pub_date = models.DateTimeField()
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_comment')
    modify_date = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(User, related_name='voter_comment')

chemblog/forms.py
from django.forms import ModelForm
from . models import Post, Comment


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ['subject', 'content']


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['comment']

chemblog/views.py
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from . models import Post, Comment
from . forms import PostForm, CommentForm
from django.utils import timezone
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db.models import Q
import logging
from pprint import pprint

import os

logger = logging.getLogger('chemblog')


def index(request):
    logger.info('INFO level message')
    page_number = request.GET.get('page', '1')
    kw = request.GET.get('kw', '')
    post_list = Post.objects.order_by('-pub_date')
    if kw:
        post_list = post_list.filter(
            Q(subject__icontains=kw) |
            Q(content__icontains=kw) |
            Q(author__username__icontains=kw) |
            Q(comment__comment__icontains=kw) |
            Q(comment__author__username__icontains=kw)
        ).distinct()  # 하나의 포스트에 달린 복수의 댓글이 모두 검색조건에 해당하는 경우, 검색결과에 동일한 포스트가 반복되어 표시되므로 중복을 제거하기 위함
    paginator = Paginator(post_list, 10)
    page_obj = paginator.get_page(page_number)
    context = {'post_list': page_obj, 'page': page_number, 'kw': kw}
    return render(request, 'chemblog/index.html', context)


def post_detail(request, post_id):
    print(type(request.user.username))
    post = get_object_or_404(Post, pk=post_id)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.pub_date = timezone.now()
            comment.post_id = post.id
            comment.save()
            return redirect('{}#comment_{}'.format(resolve_url('chemblog:post_detail', post_id=post.id), comment.id))
    # Sort by
    if request.GET.get('sortby') == 'best':
        comment_list = post.comment_set.all().order_by('-voter')
    else:
        comment_list = post.comment_set.all().order_by('-pub_date')
    # comment_list = Comment.objects.order_by('-pub_date') 로 코딩하는 실수를 하여
    # 각각의 post entry 마다 모든 comment 객체가 나타났었음
    page_number = request.GET.get('page', 1)
    paginator = Paginator(comment_list, 10)
    page_obj = paginator.get_page(page_number)
    context = {'post': post, 'page_obj': page_obj}
    response = render(request, 'chemblog/post_detail.html', context)

    # hits number representing by using cookie
    cookie_value = request.COOKIES.get('hitsnumber', '_')
    max_age = 24 * 60 * 60

    # increment of hits number for a post by each authenticated(= being login) user
    if request.user.username not in cookie_value:
        if request.user.is_authenticated:
            cookie_value += f"{request.user.username.encode('utf-8')}_"
            post.hits += 1
        else:
            if f'_{post_id}_' not in cookie_value:
                cookie_value += f'{post_id}_'
                post.hits += 1

        post.save()
        response.set_cookie('hitsnumber', value=cookie_value, httponly=True)

    return response

    # user 관계없이 조회수 설정할 경우의 코드
    '''if f'_{post_id}_' not in cookie_value:
        cookie_value += f'{post_id}_'
        response.set_cookie('hitsnumber', value=cookie_value, httponly=True)
        post.hits += 1
        # post.hits = F('hits') + 1 코드로 동일한 결과를 얻지만, 데이터베이스상에서 처리하므로 메모리를 사용치 않는다고 함
        post.save()

    return response'''


@login_required(login_url='common:login')
def post_create(request):
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.pub_date = timezone.now()
            post.save()
            return redirect('chemblog:index')
    else:
        form = PostForm()
    return render(request, 'chemblog/post_form.html', {'form': form})


@login_required(login_url='common:login')
def post_modify(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.user != post.author:
        messages.error(request, 'You are not authorized to make this modification')
        return redirect('chemblog:post_detail', post_id=post.id)
    if request.method == 'POST':
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.modify_date = timezone.now()
            post.save()
            return redirect('chemblog:post_detail', post_id=post.id)

    else:
        form = PostForm(instance=post)
    # 만약 여기서 else를 생략하면 form.is_valid()가 False인 경우에도 템플릿에서 구현한 오류 메시지가 나타나지 않는다.
    # 그 이유는 form.is_valid()가 False 이면 form = PostForm(instance=post)가 렌더링 되기 때문이다.
    # 하지만 else 가 있다면 당연히 form = PostForm(instance=post)을 건너뛰고 그 아래의 return 구문을 실행한다는 뜻이다.
    return render(request, 'chemblog/post_form.html', {'form': form})


@login_required(login_url='common:login')
def post_delete(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.user != post.author:
        messages.error(request, 'You are not authorized to make this modification')
        return redirect('chemblog:post_detail', post_id=post.id)
    post.delete()
    return redirect('chemblog:index')


@login_required(login_url='common:login')
def post_vote(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.user == post.author:
        messages.error(request, "Cannot make recommendation for one's own post")
    else:
        post.voter.add(request.user)
    return redirect('chemblog:post_detail', post_id=post.id)


@login_required(login_url='common:login')
def comment_vote(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user == comment.author:
        messages.error(request, "Cannot make recommendation for your own comment")
    else:
        comment.voter.add(request.user)
    return redirect('{}#comment_{}'.format(resolve_url('chemblog:post_detail', post_id=comment.post.id), comment.id))


@login_required(login_url='common:login')
def comment_delete(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, 'You are not authorized to remove this comment')
    else:
        comment.delete()
    return redirect('chemblog:post_detail', post_id=comment.post.id)

templates/chemblog/index.html
{% extends 'base.html' %}
{% block content %}
{% load chemblog_extra %}

<div class="container my-3">
    <div class="row my-3">
        <div class="col-6">
            <a href="{% url 'chemblog:post_create' %}" class="btn btn-primary">Create a New</a>
        </div>
        <div class="col-6">
            <div class="input-group">
                <input type="text" id="search_kw" class="form-control" value="{{ kw|default_if_none:'' }}">
                <button class="btn btn-outline-secondary" type="button" id="btn_search">Search</button>
            </div>
        </div>
    </div>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">No.</th>
                <th scope="col">Subject</th>
                <th scope="col">Username</th>
                <th scope="col">Published</th>
                <th scope="col">Visited</th>
            </tr>
        </thead>
        {% if post_list %}
        {% for post in post_list %}
        <tbody>
            <tr>
                <th scope="row">
                    {{ post_list.paginator.count|sub:post_list.start_index|sub:forloop.counter0|add:1 }}</th>
                <td>
                    <a href="{% url 'chemblog:post_detail' post.id %}">{{ post.subject }}</a>
                    {% if post.comment_set.count > 0 %}
                    <button type="button" class="btn btn-sm ms-5">
                        comments<span class="badge text-bg-primary ms-2">{{ post.comment_set.count }}</span>
                    </button>
                    {% endif %}
                </td>
                <td>{{ post.author.username }}</td>
                <td>{{ post.pub_date }}</td>
                <td>{{ post.hits }}</td>
            </tr>
        </tbody>
        {% endfor %}
        {% else %}
        <p>No posts are available</p>
        {% endif %}
    </table>
    <nav class="my-3">
        <ul class="pagination justify-content-center">
            {% if post_list.has_previous %}
            <li class="page-item"><a class="page-link" data-page="{{ post_list.previous_page_number }}"
                href="javascript:void(0)">Previous</a>
            </li>
            {% else %}
            <li class="page-item disabled"><a class="page-link" tabindex="-1">Previous</a></li>
            {% endif %}
            {% for page in post_list.paginator.page_range %}
            {% if page >= post_list.number|add:'-5' and page <= post_list.number|add:'5' %}
            {% if page == post_list.number %}
            <li class="page-item active"><a class="page-link" data-page="{{ page }}"
                href="javascript:void(0)">{{ page }}</a></li>
            {% else %}
            <li class="page-item"><a class="page-link" data-page="{{ page }}"
                href="javascript:void(0)">{{ page }}</a></li>
            {% endif %}
            {% endif %}
            {% endfor %}
            {% if post_list.has_next %}
            <li class="page-item"><a class="page-link" data-page="{{ post_list.next_page_number }}"
                href="javascript:void(0)">Next</a></li>
            {% else %}
            <li class="page-item disabled"><a class="page-link" tabindex="-1">Next</a></li>
            {% endif %}
        </ul>
    </nav>
</div>
<form id="searchForm" method="get" action="{% url 'chemblog:index' %}">
    <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
    <input type="hidden" id="page" name="page" value="{{ page }}">
</form>
{% endblock %}
{% block script %}
<script type="text/javascript">
    const page_elements = document.getElementsByClassName('page-link');
    Array.from(page_elements).forEach(function(element){
        element.addEventListener('click', function(){
            document.getElementById('page').value = this.dataset.page;
            document.getElementById('searchForm').submit();
        });
    });
    const btn_search = document.getElementById('btn_search');
    btn_search.addEventListener('click', function() {
        document.getElementById('kw').value = document.getElementById('search_kw').value;
        document.getElementById('page').value = 1;
        document.getElementById('searchForm').submit();
    });
</script>
{% endblock %}

templates/chemblog/post_detail.html
{% extends 'base.html' %}
{% block content %}
{% load chemblog_extra %}
<style>
    pre {
    background-color: #F0F0F0;
    }
</style>
<div class="container my-3">
    <!-- message 표시 -->
    {% if messages %}
    <div class="alert alert-danger my-3" role="alert">
        {% for message in messages %}
        <strong>{{ message.tags }}</strong>
        <ul>
            <li>{{ message.message }}</li>
        </ul>
        {% endfor %}
    </div>
    {% endif %}
  <h2 class="border-bottom py-2">{{ post.subject }}
      <span class="badge bg-primary">
          <h6>{{ post.author.username }}</h6>
      </span>
  </h2>
    <div class="card my-5">
        <div class="card-body">
            <div class="card-text rows=10">{{ post.content|mark }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge bg-light text-dark p-2">
                    {{ post.pub_date }}
                </div>
            </div>
            <div class="my-3">
                <a href="javascript:void(0)" data-uri="{% url 'chemblog:post_vote' post.id %}"
                   class="recommend btn btn-sm btn-outline-secondary">Recommend
                    <span class="badge rounded-pill bg-success">{{ post.voter.count }}</span>
                </a>
                {% if request.user == post.author %}
                <a href="{% url 'chemblog:post_modify' post.id %}" class="btn btn-sm btn-outline-secondary">
                    Modify
                </a>
                <a href="javascript:void(0)" data-uri="{% url 'chemblog:post_delete' post.id %}"
                   class="delete btn btn-sm btn-outline-secondary">
                    Delete
                </a>
                {% endif %}
            </div>
        </div>
    </div>

    <!-- Comment -->
    <h5>{{ post.comment_set.count }} comments included </h5>
    <!-- Example single danger button -->
    <div class="btn-group my-2">
        <button type="button" class="btn btn-primary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
            Sort by
        </button>
        <form action="{% url 'chemblog:post_detail' post.id %}" method="get">
            <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="?sortby=best">Best</a></li>
                <li><a class="dropdown-item" href="{% url 'chemblog:post_detail' post.id %}">New</a></li>
        </form>
    </div>
    {% for comment in page_obj %}
    <a id="comment_{{ comment.id }}"></a>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text">
                {{ page_obj.paginator.count|sub:page_obj.start_index|sub:forloop.counter0|add:'1' }} <br>
                page_obj.paginator.count : {{ page_obj.paginator.count }} <br>
                start_index : {{ page_obj.start_index }} <br>
                forloop.counter0 : {{ forloop.counter0 }} <br>
                {{ comment.comment|mark }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge bg-light text-dark p-2 text-start">
                    <div class="mb-2">{{ comment.author.username }}</div>
                    <div>{{ comment.pub_date }}</div>
                </div>
            </div>
            <div class="my-3">
                <a href="javascript:void(0)" data-uri="{% url 'chemblog:comment_vote' comment.id %}"
                    class="recommend btn btn-sm btn-outline-secondary">Recommend
                    <span class="badge rounded-pill bg-success">{{ comment.voter.count }}</span>
                </a>
                {% if request.user == comment.author %}
                <a href="javascript:void(0)" data-uri="{% url 'chemblog:comment_delete' comment.id %}"
                   class="delcom btn btn-sm btn-outline-secondary">Delete
                </a>
                {% endif %}
            </div>
        </div>
    </div>
    {% endfor %}
    <nav>
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link">Previous</a>
            {% endif %}
            </li>
            {% for page in page_obj.paginator.page_range %}
            {% if page >= page_obj.number|add:'-5' and page <= page_obj.number|add:'5' %}
            {% if page == page_obj.number %}
            <li class="page-item active">
                <a class="page-link" href="?page={{ page }}">{{ page }}</a>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" href="?page= {{ page }}">{{ page }}</a>
            </li>
            {% endif %}
            {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link">Next</a>
            </li>
            {% endif %}
        </ul>
    </nav>
    <form method="post">
        {% csrf_token %}
        <div class="mt-3">
            <label for="comment" class="form-label">Comments</label>
            <textarea {% if not user.is_authenticated %}disabled{% endif %}
                      id="comment" name="comment" class="form-control" rows="1"></textarea>
            {% if not user.is_authenticated %}
            <p>To make a comment, you need to
                <a href="{% url 'common:login' %}?next={{request.path}}">login</a>
            </p>
            {% endif %}
            <input type="submit" value="Make a comment" class="btn btn-primary btn-sm mt-3">
        </div>
    </form>
</div>
{% endblock %}
{% block script %}
<script type="text/javascript">
    const delete_elements = document.getElementsByClassName("delete");
    Array.from(delete_elements).forEach(function(element) {
        element.addEventListener('click', function(){
            if(confirm("Are you sure to delete this post?")){
                location.href = this.dataset.uri;
            };
        });
    });
    const recommend_elements = document.getElementsByClassName("recommend");
    Array.from(recommend_elements).forEach(function(element){
        element.addEventListener('click', function() {
            if(confirm('Are you sure to make a recommendation?')){
                location.href = this.dataset.uri;
            };
        });
    });
    const delcom_elements = document.getElementsByClassName("delcom");
    Array.from(delcom_elements).forEach(function(element){
        element.addEventListener('click', function() {
            if(confirm('Are you sure to remove the comment?')){
                location.href = this.dataset.uri;
            };
        });
    });
</script>
{% endblock %}

templates/chemblog/post_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <form method="post">
        {% csrf_token %}

        <!-- 오류표시 Start -->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field in form %}
            {% if field.errors %}
            <div>
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
            </div>
            {% endif %}
            {% endfor %}
        </div>
        {% endif %}
        <!-- 오류표시 End -->

        <div class="mb-3">
            <label for="subject" class="form-label">Title</label>
            <input type="text" class="form-control" id="subject" name="subject"
                    value="{{ form.subject.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="content" class="form-label">Content</label>
            <textarea id="content" class="form-control" name="content" rows="20">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <input type="submit" class="btn btn-primary my-3" value="Submit">
    </form>
</div>
{% endblock %}
{% block script %}

<!-- simplemde editor -->
<script>
    var simplemde = new SimpleMDE({ element: document.getElementById("content") });
</script>
{% endblock %}