chemblog/urls.py
from django.urls import path
from . import views

app_name = 'chemblog'

urlpatterns = [
    path('', views.index, name='index'),
    path('post/<int:post_id>/', views.post_detail, name='post_detail'),
    path('post/create/', views.post_create, name='post_create'),
    path('post/modify/<int:post_id>', views.post_modify, name='post_modify'),
    path('post/delete/<int:post_id>', views.post_delete, name='post_delete'),
    path('post/vote/<int:post_id>', views.post_vote, name='post_vote'),
    path('comment/vote/<int:comment_id>', views.comment_vote, name='comment_vote'),
    path('comment/delete<int:comment_id>', views.comment_delete, name='comment_delete'),
]

common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from django.utils import timezone


class DynamicContextLoginView(auth_views.LoginView):
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['time'] = timezone.now()
        return context


app_name = 'common'

urlpatterns = [
    path('naverlogin_reprompt', views.naverlogin_reprompt, name='naverlogin_reprompt'),
    path('signup_naver/<str:access_token>/', views.signup_naver, name='signup_naver'),
    path('naverlogin/', views.naverlogin, name='naverlogin'),
    path('navercallback/', views.navercallback, name='navercallback'),
    path('user_profile/', views.user_profile, name='user_profile'),
    path('signup_kakao/<str:access_token>/', views.signup_kakao, name='signup_kakao'),
    path('login/', DynamicContextLoginView.as_view(template_name='common/login.html'), name='login'),
    path('kakaologin/', views.kakaologin, name='kakaologin'),
    path('kakaocallback/', views.kakaocallback, name='kakaocallback'),
    path('logout/', auth_views.LogoutView.as_view(template_name='chemblog/index.html'), name='logout'),
    path('signup/', views.signup, name='signup'),
    path('password_reset/', auth_views.PasswordResetView.as_view(
        email_template_name='common/password_reset_email.html', success_url='done'
    ),
         name='password_reset'
         ),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password_reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        success_url='http://localhost:8000/common/password_reset_complete/'
    ),
         name='password_reset_confirm'),
    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('chemblog/', include('chemblog.urls')),
    path('common/', include('common.urls')),
    path('socialaccounts/', include('allauth.urls')),
]

handler404 = 'common.views.page_not_found'
handler500 = 'common.views.server_error'

common/models.py
from django.db import models

# Create your models here.

common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserForm(UserCreationForm):
    email = forms.EmailField(label='email')

    class Meta:
        model = User
        fields = ('username', 'password1', 'password2', 'email')

common/views.py
import json
import logging
import os
from pprint import pprint
from urllib.parse import urlencode, quote
from urllib.request import urlopen, Request
from urllib.error import HTTPError, URLError

from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect

from config.settings import base
from .forms import UserForm
from .urlopen_try_except import urlopen_request
from .social_user_signup import social_user_signup
from django.contrib.auth.models import User
import logging

logger = logging.getLogger('chemblog')


def signup(request):
    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(request, username=username, password=raw_password)
            login(request, user)
            return redirect('chemblog:index')
    else:
        form = UserForm()
    return render(request, 'common/signup.html', {'form': form})


secret_file = os.path.join(base.BASE_DIR, 'secrets.json')
with open(secret_file) as f:
    secrets = json.loads(f.read())


def redirect_sociallogin(env, provider):
    local = 'http://127.0.0.1:8000/common/'
    prod = 'https://chemia.kr/common/'
    if provider == 'kakao':
        path = 'kakaocallback'
    elif provider == 'naver':
        path = 'navercallback'
    return local if env == 'local' else prod, path


def kakaologin(request):
    client_id = base.get_secret('client_id_kakao')
    host_with_protocol, path = redirect_sociallogin(request.get_host()[:5], 'kakao')
    redirect_uri = host_with_protocol + path
    url = f'https://kauth.kakao.com/oauth/authorize' \
          f'?response_type=code&client_id={client_id}&redirect_uri={redirect_uri}'
    return redirect(url)


def kakaocallback(request, headers=None):
    client_id = base.get_secret('client_id_kakao')
    host_with_protocol, path = redirect_sociallogin(request.get_host()[:5], 'kakao')
    redirect_uri = host_with_protocol + path
    code = request.GET.get('code')
    print(code)
    url = 'https://kauth.kakao.com/oauth/token'
    data = {
        'grant_type': 'authorization_code',
        'client_id': client_id,
        'redirection_uri': redirect_uri,
        'code': code
    }
    encdata = urlencode(data)
    postdata = encdata.encode('utf-8')
    request = Request(url, headers=headers or {}, data=postdata)

    resp_as_dic = urlopen_request(request)
    access_token = resp_as_dic['access_token']

    return redirect('common:signup_kakao', access_token)
    # with 구문을 사용치 않아 (HTTPResponse 객체가 opening 후에 closing이 안되어) 에러가 난것으로 알았으나 다음과 같이 with 없는 코드
    # 로도 위의 코드와 같은 결과를 얻음
    '''response = urlopen(request, timeout=10)
        body = response.read()
        response_json = body.decode('utf-8')
        response_dic = json.loads(response_json)
        access_token = response_dic['access_token']
        print(f'access_token : {access_token}')
        return redirect('chemblog/index')'''


def signup_kakao(request, access_token):
    url = "https://kapi.kakao.com/v2/user/me"
    authorization = f'Bearer ${access_token}'
    headers = {"Authorization": authorization}
    req = Request(url, headers=headers)

    resp_as_dic = urlopen_request(req)
    pprint(resp_as_dic)

    username = resp_as_dic['properties']['nickname']
    email = resp_as_dic['kakao_account']['email']

    user = social_user_signup(username, email)
    
    login(request, user, backend='django.contrib.auth.backends.ModelBackend')

    return redirect('chemblog:index')


def naverlogin(request):
    client_id = base.get_secret('client_id_naver')
    host_with_protocol, path = redirect_sociallogin(request.get_host()[:5], 'naver')
    redirect_uri = host_with_protocol + path
    urlencoded_redirect_uri = quote(redirect_uri)
    state_stirng = request.POST.get('csrfmiddlewaretoken')

    base.update_secret('state', state_stirng)

    csrf_token = base.get_secret('state')
    logger.info(f'{state_stirng} from GET, {csrf_token} from secrets.json')

    url_naverlogin = f'https://nid.naver.com/oauth2.0/authorize?response_type=code&' \
                     f'client_id={client_id}&state={state_stirng}&redirect_uri={urlencoded_redirect_uri}'
    return redirect(url_naverlogin)


def inner_urlopen(url, data):
    try:
        with urlopen(url, bytes(data, encoding='utf-8')) as response:
            body = response.read()
    except HTTPError as error:
        print(error.status, error.reason)
    except URLError as error:
        print(error.reason)
    else:
        res_as_dic = json.loads(body)
        return res_as_dic


def navercallback(request):
    from config.settings import base
    # 네이버 로그인 버튼을 눌렀을 때 전달된 csrf token
    csrf_token = base.get_secret('state')

    logger.info('csrf token: %s', csrf_token)
    logger.info("request.GET.get('state'): %s", request.GET.get('state'))

    # 위의 토큰 값과 콜백으로 전달 받은 토큰값 일치 여부
    if csrf_token == request.GET.get('state'):
        url = 'https://nid.naver.com/oauth2.0/token'
        params = {
            'grant_type': 'authorization_code',
            'client_id': base.get_secret('client_id_naver'),
            'client_secret': base.get_secret('client_secret_naver'),
            'code': request.GET.get('code'),
        }
        data = urlencode(params)
        response = inner_urlopen(url, data)
        access_token = response['access_token']
        return redirect('common:signup_naver', access_token)
    else:
        return render(request, 'common/400.html')


def signup_naver(request, access_token):
    url = 'https://openapi.naver.com/v1/nid/me'
    authorization = f'Bearer {access_token}'
    req = Request(url, headers={'Authorization': authorization})
    resp_as_dic = urlopen_request(req)
    pprint(resp_as_dic)
    username = resp_as_dic['response']['nickname']
    email = resp_as_dic['response']['email']

    user = social_user_signup(username, email)
    login(request, user, backend='django.contrib.auth.backends.ModelBackend')

    return redirect('chemblog:index')


def naverlogin_reprompt(request):
    client_id = base.get_secret('client_id_naver')
    host_with_protocol, path = redirect_sociallogin(request.get_host()[:5], 'naver')
    redirect_uri = host_with_protocol + path
    urlencoded_redirect_uri = quote(redirect_uri)
    state_string = request.POST.get('csrfmiddlewaretoken')

    base.update_secret('state', state_string)

    url_reprompt = f'https://nid.naver.com/oauth2.0/authorize?response_type=code&client_id={client_id}&' \
                   f'state={state_string}&redirect_uri={urlencoded_redirect_uri}&auth_type=reprompt'

    return redirect(url_reprompt)


def user_profile(request):
    user = User.objects.get(id=request.user.id)
    user_post = user.author_post.all()
    user_comment = user.author_comment.all()
    context = {
        'user_post': user_post,
        'user_comment': user_comment
    }
    return render(request, 'common/user_profile.html', context)


def page_not_found(request, exception):
    return render(request, 'common/404.html', {})


def server_error(request):
    return render(request, 'common/500.html', {})

templates/common/access_token.html
{{ profile }}

templates/common/login.html
{% extends 'base.html' %}
{% load socialaccount %}
{% load static %}
{% block content %}

<div class="container my-3">
    <form method="post" action="{% url 'common:login' %}">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ next }}">
        {% include 'form_errors.html' %}
        <div class="mb-3">
            <label for="username" class="form-label mb-3">Username</label>
            <input id="username" name="username" class="form-control mb-3"
            value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="password" class="form-label mb-3">Password</label>
            <input id="password" type="password" name="password" class="form-control mb-3"
                   value="{{ form.password.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">Log In</button>
        <p class="my-3">Forgot your
            <a href="{% url 'common:password_reset' %}" style="text-decoration:none">
            <span style="color:blue;" >password?</span>
            </a>
        </p>
    </form>

    <!-- social login start -->
    <div class="mt-3">
        <a href="{% provider_login_url 'google' %}" >
            <img src="{% static 'images/btn_google_signin_light_focus_web.png' %}?prevention_cache={{ time }}">
        </a>
    </div>
    <div class="mt-3">
        <a href="{% url 'common:kakaologin' %}">
            <img src="{% static 'images/kakao_login_medium_narrow.png' %}?prevention_cache={{ time }}">
        </a>
    </div>
    <div class="mt-3">
        <span>
        <form id="naverlogin" action="{% url 'common:naverlogin' %}" method="post">
            {% csrf_token %}
            <input type="image" src="{% static 'images/btnG_official.png' %}?prevention_cache={{ time }}">
        </form>
        <form action="{% url 'common:naverlogin_reprompt' %}" method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-primary mb-3">Update Information for Naver!</button>
        </form>
        </span>
    </div>
    {{ time }} <br>
    {% now 'jS F Y H:i' %}

    <!-- social login end -->

</div>

{% endblock %}


{% block script %}
<!--
<script type="text/javascript">
    const input_csrftoken = document.forms['naverlogin'].elements['naverlogin']
    input_csrftoken.value = document.querySelector('[name=csrfmiddlewaretoken]').value
</script>
-->
{% endblock %}

templates/common/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'common:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

templates/common/signup.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <form method="post" action="{% url 'common:signup' %}">
        {% csrf_token %}
        {% include 'form_errors.html' %}
        <div class="mb-3">
            <label for="username" class="form-label">Username</label>
            <input type="text" id="username" name="username" class="form-control"
                    value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="password1" class="form-label">Password</label>
            <input type="password" id="password1" name="password1" class="form-control"
                    value="{{ form.password1.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="password2" class="form-label">Password confirmation</label>
            <input type="password" id="password2" name="password2" class="form-control"
                    value="{{ form.password2.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="email" class="form-label">email</label>
            <input type="email" id="email" name="email" class="form-control"
                    value="{{ form.email.value|default_if_none:'' }}">
        </div>
        <input type="submit" class="btn btn-primary" value="registration">
    </form>
</div>
{% endblock %}

templates/common/user_profile.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
  <ul class="nav nav-tabs" id="myTab" role="tablist">
    <li class="nav-item" role="presentation">
      <button class="nav-link active" id="home-tab" data-bs-toggle="tab" data-bs-target="#home-tab-pane" type="button" role="tab" aria-controls="home-tab-pane" aria-selected="true">
        Basic information</button>
    </li>
    <li class="nav-item" role="presentation">
      <button class="nav-link" id="profile-tab" data-bs-toggle="tab" data-bs-target="#profile-tab-pane" type="button" role="tab" aria-controls="profile-tab-pane" aria-selected="false">
        Post</button>
    </li>
    <li class="nav-item" role="presentation">
      <button class="nav-link" id="contact-tab" data-bs-toggle="tab" data-bs-target="#contact-tab-pane" type="button" role="tab" aria-controls="contact-tab-pane" aria-selected="false">
        Comment</button>
    </li>
  </ul>
  <div class="tab-content" id="myTabContent">
    <div class="tab-pane fade show active" id="home-tab-pane" role="tabpanel" aria-labelledby="home-tab" tabindex="0">
      <div class="container my-3">
        <h6 class="fw-bold">Name</h6>
        <p class="mb-4">{{ user.username }}</p>
        <h6 class="fw-bold">Email</h6>
        <p class="mb-4">{{ user.email }}</p>
        <h6 class="fw-bold">Date joined</h6>
        <p class="mb-4">{{ user.date_joined }}</p>
        <h6 class="fw-bold">Last login</h6>
        <p class="mb-4">{{ user.last_login }}</p>
      </div>
    </div>
  <!-- post -->
    <div class="tab-pane fade" id="profile-tab-pane" role="tabpanel" aria-labelledby="profile-tab" tabindex="0">
      <table class="table mt-5">
        <thead>
          <tr>
            <th scope="col">No.</th>
            <th scope="col">Subject</th>
            <th scope="col">Published</th>
          </tr>
        </thead>
        {% if user_post %}
        {% for post in user_post %}
        <tbody>
          <tr>
            <td>{{ forloop.revcounter }}</td>
            <td><a href="{% url 'chemblog:post_detail' post.id %}">{{ post.subject }}</a></td>
            <td>{{ post.pub_date }}</td>
          </tr>
        </tbody>
        {% endfor %}
        {% else %}
        <p class="mt-3"><h5 class="ms-3">You hasn't posted anything!</h5></p>
        {% endif %}
      </table>
    </div>
  <!-- comment -->
    <div class="tab-pane fade" id="contact-tab-pane" role="tabpanel" aria-labelledby="contact-tab" tabindex="0">
      <table class="table mt-5">
        <thead>
          <tr>
            <th scope="col">No.</th>
            <th scope="col">Comment</th>
            <th scope="col">Published</th>
            <th scope="col">Post</th>
          </tr>
        </thead>
        {% if user_comment %}
        {% for comment in user_comment %}
        <tbody>
          <tr>
            <td>{{ forloop.revcounter }}</td>
            <td>{{ comment.comment }}</td>
            <td>{{ comment.pub_date }}</td>
            <td><a href="{% url 'chemblog:post_detail' comment.post.id %}">{{ comment.post.subject }}</a></td>
          </tr>
        </tbody>
        {% endfor %}
        {% else %}
        <p class="mt-3"><h5 class="ms-3">You hasn't posted anything!</h5></p>
        {% endif %}
      </table>
    </div>
  </div>
</div>
{% endblock %}