chemblog/urls.py
from django.urls import path
from . import views

app_name = 'chemblog'

urlpatterns = [
    path('', views.index, name='index'),
    path('post/<int:post_id>/', views.post_detail, name='post_detail'),
    path('post/create/', views.post_create, name='post_create'),
    path('post/modify/<int:post_id>', views.post_modify, name='post_modify'),
    path('post/delete/<int:post_id>', views.post_delete, name='post_delete'),
    path('post/vote/<int:post_id>', views.post_vote, name='post_vote'),
    path('comment/vote/<int:comment_id>', views.comment_vote, name='comment_vote'),
    path('comment/delete<int:comment_id>', views.comment_delete, name='comment_delete'),
]

common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from django.utils import timezone


class DynamicContextLoginView(auth_views.LoginView):
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['time'] = timezone.now()
        return context


app_name = 'common'

urlpatterns = [
    path('naverlogin_reprompt', views.naverlogin_reprompt, name='naverlogin_reprompt'),
    path('signup_naver/<str:access_token>/', views.signup_naver, name='signup_naver'),
    path('naverlogin/', views.naverlogin, name='naverlogin'),
    path('navercallback/', views.navercallback, name='navercallback'),
    path('user_profile/', views.user_profile, name='user_profile'),
    path('signup_kakao/<str:access_token>/', views.signup_kakao, name='signup_kakao'),
    path('login/', DynamicContextLoginView.as_view(template_name='common/login.html'), name='login'),
    path('kakaologin/', views.kakaologin, name='kakaologin'),
    path('kakaocallback/', views.kakaocallback, name='kakaocallback'),
    path('logout/', auth_views.LogoutView.as_view(template_name='chemblog/index.html'), name='logout'),
    path('signup/', views.signup, name='signup'),
    path('password_reset/', auth_views.PasswordResetView.as_view(
        email_template_name='common/password_reset_email.html', success_url='done'
    ),
         name='password_reset'
         ),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password_reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        success_url='http://localhost:8000/common/password_reset_complete/'
    ),
         name='password_reset_confirm'),
    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('chemblog/', include('chemblog.urls')),
    path('common/', include('common.urls')),
    path('socialaccounts/', include('allauth.urls')),
]

handler404 = 'common.views.page_not_found'
handler500 = 'common.views.server_error'

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Welcome to Chemia's ChemBlog</title>
</head>
<body>
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'simplemde.min.css' %}">
{% include 'navbar.html' %}
{% block content %}
{% endblock %}
<!-- Bootstrap JS -->
<script src="{% static 'bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'simplemde.min.js' %}"></script>
<!-- Javascript start here -->
{% block script %}
{% endblock %}
<!-- Javascript End -->
</body>
</html>

templates/form_errors.html
<!-- Prit out that both Field and Non-Field errors -->
{% if form.errors %}
<div class="alert alert-danger">
    {% for field in form %}
    <!-- Field errors -->
    {% if field.errors %}
    <div>
        <strong>{{ field.label }}</strong>
        {{ field.errors }}
    </div>
    {% endif %}
    {% endfor %}
    <!-- Non-Field error -->
    {% for error in form.non_field_errors %}
    <div>
        <strong>{{ error }}</strong>
    </div>
    {% endfor %}
</div>
{% endif %}

templates/navbar.html
<nav class="navbar navbar-expand-lg bg-light border-bottom">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'chemblog:index' %}">Chemia</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#nvb">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="nvb">
            <div class="navbar-nav">
                {% if user.is_authenticated %}
                <a class="nav-link" href="{% url 'common:logout' %}">{{ user.username }} (Log Out)</a>
                <a class="nav-link" href="{% url 'common:user_profile' %}">MY</a>
                {% else %}
                <a class="nav-link" href="{% url 'common:login' %}">Log In</a>
                {% endif %}
                {% if not user.is_authenticated %}
                <a href="{% url 'common:signup' %}" class="nav-link">Sign up</a>
                {% endif %}
            </div>
        </div>
    </div>
</nav>